### ISSUE TITLE
有个想法 将得到的第一个IP写入网络接口后让ddns获取

### ISSUE THREAD

**Issue by lijiazhiren** [mingxiaoyu/luci-app-cloudflarespeedtest#1]
在自己有设置ddns的情况下 域名 abc.cde.com
在网络-接口里新建一个接口 命名-123
然后每次优选得到的第一个IP写入网络接口-123 
再让ddns获取网络接口-123的ip
这样不管在什么设备上 只要是abc.cde.com就可以使用这个优选IP了

小白一个 不知道这个想法能不能实现

**Comment by mingxiaoyu** [comment]
感觉可行

**Comment by lijiazhiren** [comment]
> 感觉可行

突然反应过来这想法没用阿  在别的网络下这IP没什么用呢
