### ISSUE TITLE
 点击 测试并应用 无反应

### ISSUE THREAD

**Issue by iulo** [mingxiaoyu/luci-app-cloudflarespeedtest#12]
版本：1.4.2
现象：点击 测试并应用 按钮，自动跳转到了日志，日志无任何输出，最佳ip处也没有显示任何东西

**Comment by mingxiaoyu** [comment]
要等一会才运行。不要那么急！我设备要等2秒之后才有开始输出日志

**Comment by iulo** [comment]
@mingxiaoyu 应该不是这个问题，ssh连上去，我看了log文件一直没有创建，如果我直接调用 `/usr/bin/cloudflarespeedtest/cloudflarespeedtest.sh start` 就正常，用页面点就没反应

**Comment by iulo** [comment]
重启了下openwrt，现在可以了  emm...有点奇怪

**Comment by mingxiaoyu** [comment]
这………………
