### ISSUE TITLE
插件运行报错

### ISSUE THREAD

**Issue by qq83184143** [mingxiaoyu/luci-app-cloudflarespeedtest#13]
你好。我运行这个插件怎么报错。
2022-03-28 09:59:27: -----------start----------
/usr/bin/cloudflarespeedtest/cloudflarespeedtest.sh: line 82: /usr/bin/cdnspeedtest: not found

**Comment by mingxiaoyu** [comment]
没装cdnspeedtest

**Comment by mingxiaoyu** [comment]
https://github.com/immortalwrt-collections/openwrt-cdnspeedtest

自己下载适合自己的
