### ISSUE TITLE
测速一直没有速度是怎么回事？

### ISSUE THREAD

**Issue by huqiwengithub** [mingxiaoyu/luci-app-cloudflarespeedtest#17]
测速一直没有速度，我自己就停掉了，用的是竞斗云路由器，正确编译的。自己做的测速反代，日志如下：

/usr/bin/cdnspeedtest -sl 10 -url https://speedtest.xmlyfq.workers.dev/vultr.com.1000MB.bin -o /usr/share/cloudflarespeedtestresult.txt -f /usr/share/CloudflareSpeedTest/ip.txt -tl 200 -tll 40 -n 200 -t 4 -dt 10 -dn 2
2022-04-12 21:36:16: -----------start----------
# XIU2/CloudflareSpeedTest v2.0.3 

开始延迟测速（模式：TCP IPv4，端口：443，平均延迟上限：200 ms，平均延迟下限：40 ms)
0 / 4931 [___________________________________________________________________________________] 0.00%0 / 4931 [___________________________________________________________________________________] 0.00%0 / 4931 [___________________________________________________________________________________] 0.00%0 / 4931 [___________________________________________________________________________________] 0.00%1 / 4931 [>__________________________________________________________________________________] 0.02%2 / 4931 [>__________________________________________________________________________________] 0.04%2 / 4931 [>__________________________________________________________________________________] 0.04%2 / 4931 [>__________________________________________________________________________________] 0.04%6 / 4931 [>__________________________________________________________________________________] 0.12%8 / 4931 [>__________________________________________________________________________________] 0.16%8 / 4931 [>__________________________________________________________________________________] 0.16%8 / 4931 [>__________________________________________________________________________________] 0.16%10 / 4931 [>_________________________________________________________________________________] 0.20%12 / 4931 [>_________________________________________________________________________________] 0.24%13 / 4931 [>_________________________________________________________________________________] 0.26%13 / 4931 [>_________________________________________________________________________________] 0.26%15 / 4931 [>_________________________________________________________________________________] 0.30%17 / 4931 [>_________________________________________________________________________________] 0.34%17 / 4931 [>_________________________________________________________________________________] 0.34%17 / 4931 [>_________________________________________________________________________________] 0.34%200 / 4931 [--->_____________________________________________________________________________] 4.06%200 / 4931 [--->_____________________________________________________________________________] 4.06%200 / 4931 [--->_____________________________________________________________________________] 4.06%205 / 4931 [--->_____________________________________________________________________________] 4.16%210 / 4931 [--->_____________________________________________________________________________] 4.26%211 / 4931 [--->_____________________________________________________________________________] 4.28%211 / 4931 [--->_____________________________________________________________________________] 4.28%215 / 4931 [--->_____________________________________________________________________________] 4.36%224 / 4931 [--->_____________________________________________________________________________] 4.54%229 / 4931 [--->_____________________________________________________________________________] 4.64%229 / 4931 [--->_____________________________________________________________________________] 4.64%229 / 4931 [--->_____________________________________________________________________________] 4.64%236 / 4931 [--->_____________________________________________________________________________] 4.79%239 / 4931 [--->_____________________________________________________________________________] 4.85%240 / 4931 [--->_____________________________________________________________________________] 4.87%240 / 4931 [--->_____________________________________________________________________________] 4.87%249 / 4931 [---->____________________________________________________________________________] 5.05%251 / 4931 [---->____________________________________________________________________________] 5.09%251 / 4931 [---->____________________________________________________________________________] 5.09%251 / 4931 [---->____________________________________________________________________________] 5.09%400 / 4931 [------>__________________________________________________________________________] 8.11%400 / 4931 [------>__________________________________________________________________________] 8.11%400 / 4931 [------>__________________________________________________________________________] 8.11%405 / 4931 [------>__________________________________________________________________________] 8.21%410 / 4931 [------>__________________________________________________________________________] 8.31%411 / 4931 [------>__________________________________________________________________________] 8.34%413 / 4931 [------>__________________________________________________________________________] 8.38%417 / 4931 [------>__________________________________________________________________________] 8.46%426 / 4931 [------>__________________________________________________________________________] 8.64%431 / 4931 [------->_________________________________________________________________________] 8.74%431 / 4931 [------->_________________________________________________________________________] 8.74%431 / 4931 [------->_________________________________________________________________________] 8.74%438 / 4931 [------->_________________________________________________________________________] 8.88%441 / 4931 [------->_________________________________________________________________________] 8.94%442 / 4931 [------->_________________________________________________________________________] 8.96%442 / 4931 [------->_________________________________________________________________________] 8.96%451 / 4931 [------->_________________________________________________________________________] 9.15%453 / 4931 [------->_________________________________________________________________________] 9.19%454 / 4931 [------->_________________________________________________________________________] 9.21%454 / 4931 [------->_________________________________________________________________________] 9.21%601 / 4931 [--------->______________________________________________________________________] 12.19%601 / 4931 [--------->______________________________________________________________________] 12.19%601 / 4931 [--------->______________________________________________________________________] 12.19%606 / 4931 [--------->______________________________________________________________________] 12.29%612 / 4931 [--------->______________________________________________________________________] 12.41%613 / 4931 [--------->______________________________________________________________________] 12.43%614 / 4931 [--------->______________________________________________________________________] 12.45%617 / 4931 [---------->_____________________________________________________________________] 12.51%626 / 4931 [---------->_____________________________________________________________________] 12.70%631 / 4931 [---------->_____________________________________________________________________] 12.80%635 / 4931 [---------->_____________________________________________________________________] 12.88%647 / 4931 [---------->_____________________________________________________________________] 13.12%656 / 4931 [---------->_____________________________________________________________________] 13.30%660 / 4931 [---------->_____________________________________________________________________] 13.38%663 / 4931 [---------->_____________________________________________________________________] 13.45%668 / 4931 [---------->_____________________________________________________________________] 13.55%686 / 4931 [----------->____________________________________________________________________] 13.91%694 / 4931 [----------->____________________________________________________________________] 14.07%697 / 4931 [----------->____________________________________________________________________] 14.14%704 / 4931 [----------->____________________________________________________________________] 14.28%826 / 4931 [------------->__________________________________________________________________] 16.75%832 / 4931 [------------->__________________________________________________________________] 16.87%833 / 4931 [------------->__________________________________________________________________] 16.89%838 / 4931 [------------->__________________________________________________________________] 16.99%852 / 4931 [------------->__________________________________________________________________] 17.28%861 / 4931 [------------->__________________________________________________________________] 17.46%864 / 4931 [-------------->_________________________________________________________________] 17.52%872 / 4931 [-------------->_________________________________________________________________] 17.68%895 / 4931 [-------------->_________________________________________________________________] 18.15%909 / 4931 [-------------->_________________________________________________________________] 18.43%914 / 4931 [-------------->_________________________________________________________________] 18.54%920 / 4931 [-------------->_________________________________________________________________] 18.66%966 / 4931 [--------------->________________________________________________________________] 19.59%984 / 4931 [--------------->________________________________________________________________] 19.96%988 / 4931 [---------------->_______________________________________________________________] 20.04%1000 / 4931 [---------------->______________________________________________________________] 20.28%1045 / 4931 [---------------->______________________________________________________________] 21.19%1058 / 4931 [---------------->______________________________________________________________] 21.46%1060 / 4931 [---------------->______________________________________________________________] 21.50%1061 / 4931 [---------------->______________________________________________________________] 21.52%1079 / 4931 [----------------->_____________________________________________________________] 21.88%1089 / 4931 [----------------->_____________________________________________________________] 22.08%1092 / 4931 [----------------->_____________________________________________________________] 22.15%1096 / 4931 [----------------->_____________________________________________________________] 22.23%1110 / 4931 [----------------->_____________________________________________________________] 22.51%1117 / 4931 [----------------->_____________________________________________________________] 22.65%1120 / 4931 [----------------->_____________________________________________________________] 22.71%1122 / 4931 [----------------->_____________________________________________________________] 22.75%1157 / 4931 [------------------>____________________________________________________________] 23.46%1169 / 4931 [------------------>____________________________________________________________] 23.71%1171 / 4931 [------------------>____________________________________________________________] 23.75%1177 / 4931 [------------------>____________________________________________________________] 23.87%1202 / 4931 [------------------->___________________________________________________________] 24.38%1221 / 4931 [------------------->___________________________________________________________] 24.76%1225 / 4931 [------------------->___________________________________________________________] 24.84%1234 / 4931 [------------------->___________________________________________________________] 25.03%1253 / 4931 [-------------------->__________________________________________________________] 25.41%1259 / 4931 [-------------------->__________________________________________________________] 25.53%1260 / 4931 [-------------------->__________________________________________________________] 25.55%1261 / 4931 [-------------------->__________________________________________________________] 25.57%1279 / 4931 [-------------------->__________________________________________________________] 25.94%1289 / 4931 [-------------------->__________________________________________________________] 26.14%1292 / 4931 [-------------------->__________________________________________________________] 26.20%1296 / 4931 [-------------------->__________________________________________________________] 26.28%1309 / 4931 [-------------------->__________________________________________________________] 26.55%1317 / 4931 [--------------------->_________________________________________________________] 26.71%1320 / 4931 [--------------------->_________________________________________________________] 26.77%1347 / 4931 [--------------------->_________________________________________________________] 27.32%1373 / 4931 [--------------------->_________________________________________________________] 27.84%1388 / 4931 [---------------------->________________________________________________________] 28.15%1394 / 4931 [---------------------->________________________________________________________] 28.27%1399 / 4931 [---------------------->________________________________________________________] 28.37%1449 / 4931 [----------------------->_______________________________________________________] 29.39%1474 / 4931 [----------------------->_______________________________________________________] 29.89%1491 / 4931 [----------------------->_______________________________________________________] 30.24%1520 / 4931 [------------------------>______________________________________________________] 30.83%1561 / 4931 [------------------------->_____________________________________________________] 31.66%1580 / 4931 [------------------------->_____________________________________________________] 32.04%1595 / 4931 [------------------------->_____________________________________________________] 32.35%1631 / 4931 [-------------------------->____________________________________________________] 33.08%1679 / 4931 [-------------------------->____________________________________________________] 34.05%1700 / 4931 [--------------------------->___________________________________________________] 34.48%1715 / 4931 [--------------------------->___________________________________________________] 34.78%1745 / 4931 [--------------------------->___________________________________________________] 35.39%1766 / 4931 [---------------------------->__________________________________________________] 35.81%1767 / 4931 [---------------------------->__________________________________________________] 35.83%1772 / 4931 [---------------------------->__________________________________________________] 35.94%1779 / 4931 [---------------------------->__________________________________________________] 36.08%1806 / 4931 [---------------------------->__________________________________________________] 36.63%1813 / 4931 [----------------------------->_________________________________________________] 36.77%1819 / 4931 [----------------------------->_________________________________________________] 36.89%1828 / 4931 [----------------------------->_________________________________________________] 37.07%1838 / 4931 [----------------------------->_________________________________________________] 37.27%1852 / 4931 [----------------------------->_________________________________________________] 37.56%1856 / 4931 [----------------------------->_________________________________________________] 37.64%1861 / 4931 [----------------------------->_________________________________________________] 37.74%1870 / 4931 [----------------------------->_________________________________________________] 37.92%1872 / 4931 [----------------------------->_________________________________________________] 37.96%1886 / 4931 [------------------------------>________________________________________________] 38.25%1899 / 4931 [------------------------------>________________________________________________] 38.51%1909 / 4931 [------------------------------>________________________________________________] 38.71%1916 / 4931 [------------------------------>________________________________________________] 38.86%1919 / 4931 [------------------------------>________________________________________________] 38.92%1945 / 4931 [------------------------------->_______________________________________________] 39.44%1966 / 4931 [------------------------------->_______________________________________________] 39.87%1967 / 4931 [------------------------------->_______________________________________________] 39.89%1970 / 4931 [------------------------------->_______________________________________________] 39.95%1979 / 4931 [------------------------------->_______________________________________________] 40.13%2006 / 4931 [-------------------------------->______________________________________________] 40.68%2013 / 4931 [-------------------------------->______________________________________________] 40.82%2019 / 4931 [-------------------------------->______________________________________________] 40.95%2027 / 4931 [-------------------------------->______________________________________________] 41.11%2038 / 4931 [-------------------------------->______________________________________________] 41.33%2052 / 4931 [-------------------------------->______________________________________________] 41.61%2056 / 4931 [-------------------------------->______________________________________________] 41.70%2061 / 4931 [--------------------------------->_____________________________________________] 41.80%2070 / 4931 [--------------------------------->_____________________________________________] 41.98%2072 / 4931 [--------------------------------->_____________________________________________] 42.02%2086 / 4931 [--------------------------------->_____________________________________________] 42.30%2099 / 4931 [--------------------------------->_____________________________________________] 42.57%2155 / 4931 [---------------------------------->____________________________________________] 43.70%2193 / 4931 [----------------------------------->___________________________________________] 44.47%2198 / 4931 [----------------------------------->___________________________________________] 44.58%2211 / 4931 [----------------------------------->___________________________________________] 44.84%2217 / 4931 [----------------------------------->___________________________________________] 44.96%2219 / 4931 [----------------------------------->___________________________________________] 45.00%2225 / 4931 [----------------------------------->___________________________________________] 45.12%2235 / 4931 [----------------------------------->___________________________________________] 45.33%2245 / 4931 [----------------------------------->___________________________________________] 45.53%2249 / 4931 [------------------------------------>__________________________________________] 45.61%2254 / 4931 [------------------------------------>__________________________________________] 45.71%2259 / 4931 [------------------------------------>__________________________________________] 45.81%2267 / 4931 [------------------------------------>__________________________________________] 45.97%2283 / 4931 [------------------------------------>__________________________________________] 46.30%2290 / 4931 [------------------------------------>__________________________________________] 46.44%2296 / 4931 [------------------------------------>__________________________________________] 46.56%2312 / 4931 [------------------------------------->_________________________________________] 46.89%2322 / 4931 [------------------------------------->_________________________________________] 47.09%2337 / 4931 [------------------------------------->_________________________________________] 47.39%2351 / 4931 [------------------------------------->_________________________________________] 47.68%2378 / 4931 [-------------------------------------->________________________________________] 48.23%2406 / 4931 [-------------------------------------->________________________________________] 48.79%2412 / 4931 [-------------------------------------->________________________________________] 48.92%2422 / 4931 [-------------------------------------->________________________________________] 49.12%2423 / 4931 [-------------------------------------->________________________________________] 49.14%2424 / 4931 [-------------------------------------->________________________________________] 49.16%2430 / 4931 [-------------------------------------->________________________________________] 49.28%2438 / 4931 [--------------------------------------->_______________________________________] 49.44%2445 / 4931 [--------------------------------------->_______________________________________] 49.58%2449 / 4931 [--------------------------------------->_______________________________________] 49.67%2454 / 4931 [--------------------------------------->_______________________________________] 49.77%2459 / 4931 [--------------------------------------->_______________________________________] 49.87%2467 / 4931 [--------------------------------------->_______________________________________] 50.03%2483 / 4931 [--------------------------------------->_______________________________________] 50.35%2490 / 4931 [--------------------------------------->_______________________________________] 50.50%2496 / 4931 [--------------------------------------->_______________________________________] 50.62%2512 / 4931 [---------------------------------------->______________________________________] 50.94%2522 / 4931 [---------------------------------------->______________________________________] 51.15%2536 / 4931 [---------------------------------------->______________________________________] 51.43%2549 / 4931 [---------------------------------------->______________________________________] 51.69%2578 / 4931 [----------------------------------------->_____________________________________] 52.28%2606 / 4931 [----------------------------------------->_____________________________________] 52.85%2612 / 4931 [----------------------------------------->_____________________________________] 52.97%2622 / 4931 [------------------------------------------>____________________________________] 53.17%2623 / 4931 [------------------------------------------>____________________________________] 53.19%2624 / 4931 [------------------------------------------>____________________________________] 53.21%2630 / 4931 [------------------------------------------>____________________________________] 53.34%2638 / 4931 [------------------------------------------>____________________________________] 53.50%2645 / 4931 [------------------------------------------>____________________________________] 53.64%2649 / 4931 [------------------------------------------>____________________________________] 53.72%2655 / 4931 [------------------------------------------>____________________________________] 53.84%2663 / 4931 [------------------------------------------>____________________________________] 54.01%2672 / 4931 [------------------------------------------>____________________________________] 54.19%2689 / 4931 [------------------------------------------->___________________________________] 54.53%2697 / 4931 [------------------------------------------->___________________________________] 54.69%2708 / 4931 [------------------------------------------->___________________________________] 54.92%2726 / 4931 [------------------------------------------->___________________________________] 55.28%2738 / 4931 [------------------------------------------->___________________________________] 55.53%2747 / 4931 [-------------------------------------------->__________________________________] 55.71%2754 / 4931 [-------------------------------------------->__________________________________] 55.85%2778 / 4931 [-------------------------------------------->__________________________________] 56.34%2806 / 4931 [-------------------------------------------->__________________________________] 56.91%2812 / 4931 [--------------------------------------------->_________________________________] 57.03%2822 / 4931 [--------------------------------------------->_________________________________] 57.23%2823 / 4931 [--------------------------------------------->_________________________________] 57.25%2824 / 4931 [--------------------------------------------->_________________________________] 57.27%2830 / 4931 [--------------------------------------------->_________________________________] 57.39%2838 / 4931 [--------------------------------------------->_________________________________] 57.55%2845 / 4931 [--------------------------------------------->_________________________________] 57.70%2849 / 4931 [--------------------------------------------->_________________________________] 57.78%2854 / 4931 [--------------------------------------------->_________________________________] 57.88%2862 / 4931 [--------------------------------------------->_________________________________] 58.04%2873 / 4931 [---------------------------------------------->________________________________] 58.26%2889 / 4931 [---------------------------------------------->________________________________] 58.59%2897 / 4931 [---------------------------------------------->________________________________] 58.75%2908 / 4931 [---------------------------------------------->________________________________] 58.97%2926 / 4931 [---------------------------------------------->________________________________] 59.34%2938 / 4931 [----------------------------------------------->_______________________________] 59.58%2946 / 4931 [----------------------------------------------->_______________________________] 59.74%2954 / 4931 [----------------------------------------------->_______________________________] 59.91%2976 / 4931 [----------------------------------------------->_______________________________] 60.35%3006 / 4931 [------------------------------------------------>______________________________] 60.96%3012 / 4931 [------------------------------------------------>______________________________] 61.08%3021 / 4931 [------------------------------------------------>______________________________] 61.27%3023 / 4931 [------------------------------------------------>______________________________] 61.31%3024 / 4931 [------------------------------------------------>______________________________] 61.33%3030 / 4931 [------------------------------------------------>______________________________] 61.45%3038 / 4931 [------------------------------------------------>______________________________] 61.61%3045 / 4931 [------------------------------------------------>______________________________] 61.75%3049 / 4931 [------------------------------------------------>______________________________] 61.83%3054 / 4931 [------------------------------------------------>______________________________] 61.93%3062 / 4931 [------------------------------------------------->_____________________________] 62.10%3073 / 4931 [------------------------------------------------->_____________________________] 62.32%3089 / 4931 [------------------------------------------------->_____________________________] 62.64%3097 / 4931 [------------------------------------------------->_____________________________] 62.81%3108 / 4931 [------------------------------------------------->_____________________________] 63.03%3126 / 4931 [-------------------------------------------------->____________________________] 63.39%3138 / 4931 [-------------------------------------------------->____________________________] 63.64%3146 / 4931 [-------------------------------------------------->____________________________] 63.80%3154 / 4931 [-------------------------------------------------->____________________________] 63.96%3176 / 4931 [-------------------------------------------------->____________________________] 64.41%3206 / 4931 [--------------------------------------------------->___________________________] 65.02%3212 / 4931 [--------------------------------------------------->___________________________] 65.14%3221 / 4931 [--------------------------------------------------->___________________________] 65.32%3223 / 4931 [--------------------------------------------------->___________________________] 65.36%3224 / 4931 [--------------------------------------------------->___________________________] 65.38%3230 / 4931 [--------------------------------------------------->___________________________] 65.50%3237 / 4931 [--------------------------------------------------->___________________________] 65.65%3245 / 4931 [--------------------------------------------------->___________________________] 65.81%3249 / 4931 [---------------------------------------------------->__________________________] 65.89%3254 / 4931 [---------------------------------------------------->__________________________] 65.99%3262 / 4931 [---------------------------------------------------->__________________________] 66.15%3273 / 4931 [---------------------------------------------------->__________________________] 66.38%3288 / 4931 [---------------------------------------------------->__________________________] 66.68%3297 / 4931 [---------------------------------------------------->__________________________] 66.86%3308 / 4931 [---------------------------------------------------->__________________________] 67.09%3326 / 4931 [----------------------------------------------------->_________________________] 67.45%3338 / 4931 [----------------------------------------------------->_________________________] 67.69%3346 / 4931 [----------------------------------------------------->_________________________] 67.86%3354 / 4931 [----------------------------------------------------->_________________________] 68.02%3376 / 4931 [------------------------------------------------------>________________________] 68.46%3405 / 4931 [------------------------------------------------------>________________________] 69.05%3412 / 4931 [------------------------------------------------------>________________________] 69.19%3421 / 4931 [------------------------------------------------------>________________________] 69.38%3423 / 4931 [------------------------------------------------------>________________________] 69.42%3424 / 4931 [------------------------------------------------------>________________________] 69.44%3430 / 4931 [------------------------------------------------------>________________________] 69.56%3437 / 4931 [------------------------------------------------------->_______________________] 69.70%3445 / 4931 [------------------------------------------------------->_______________________] 69.86%3449 / 4931 [------------------------------------------------------->_______________________] 69.95%3454 / 4931 [------------------------------------------------------->_______________________] 70.05%3462 / 4931 [------------------------------------------------------->_______________________] 70.21%3473 / 4931 [------------------------------------------------------->_______________________] 70.43%3486 / 4931 [------------------------------------------------------->_______________________] 70.70%3497 / 4931 [-------------------------------------------------------->______________________] 70.92%3508 / 4931 [-------------------------------------------------------->______________________] 71.14%3525 / 4931 [-------------------------------------------------------->______________________] 71.49%3538 / 4931 [-------------------------------------------------------->______________________] 71.75%3546 / 4931 [-------------------------------------------------------->______________________] 71.91%3554 / 4931 [-------------------------------------------------------->______________________] 72.07%3575 / 4931 [--------------------------------------------------------->_____________________] 72.50%3605 / 4931 [--------------------------------------------------------->_____________________] 73.11%3612 / 4931 [--------------------------------------------------------->_____________________] 73.25%3621 / 4931 [---------------------------------------------------------->____________________] 73.43%3623 / 4931 [---------------------------------------------------------->____________________] 73.47%3624 / 4931 [---------------------------------------------------------->____________________] 73.49%3630 / 4931 [---------------------------------------------------------->____________________] 73.62%3635 / 4931 [---------------------------------------------------------->____________________] 73.72%3645 / 4931 [---------------------------------------------------------->____________________] 73.92%3649 / 4931 [---------------------------------------------------------->____________________] 74.00%3654 / 4931 [---------------------------------------------------------->____________________] 74.10%3668 / 4931 [---------------------------------------------------------->____________________] 74.39%3673 / 4931 [---------------------------------------------------------->____________________] 74.49%3686 / 4931 [----------------------------------------------------------->___________________] 74.75%3697 / 4931 [----------------------------------------------------------->___________________] 74.97%3708 / 4931 [----------------------------------------------------------->___________________] 75.20%3735 / 4931 [----------------------------------------------------------->___________________] 75.75%3738 / 4931 [----------------------------------------------------------->___________________] 75.81%3746 / 4931 [------------------------------------------------------------>__________________] 75.97%3754 / 4931 [------------------------------------------------------------>__________________] 76.13%3775 / 4931 [------------------------------------------------------------>__________________] 76.56%3805 / 4931 [------------------------------------------------------------>__________________] 77.16%3812 / 4931 [------------------------------------------------------------->_________________] 77.31%3821 / 4931 [------------------------------------------------------------->_________________] 77.49%3823 / 4931 [------------------------------------------------------------->_________________] 77.53%3824 / 4931 [------------------------------------------------------------->_________________] 77.55%3830 / 4931 [------------------------------------------------------------->_________________] 77.67%3835 / 4931 [------------------------------------------------------------->_________________] 77.77%3844 / 4931 [------------------------------------------------------------->_________________] 77.96%3849 / 4931 [------------------------------------------------------------->_________________] 78.06%3854 / 4931 [------------------------------------------------------------->_________________] 78.16%3868 / 4931 [------------------------------------------------------------->_________________] 78.44%3873 / 4931 [-------------------------------------------------------------->________________] 78.54%3886 / 4931 [-------------------------------------------------------------->________________] 78.81%3897 / 4931 [-------------------------------------------------------------->________________] 79.03%3908 / 4931 [-------------------------------------------------------------->________________] 79.25%3935 / 4931 [--------------------------------------------------------------->_______________] 79.80%3937 / 4931 [--------------------------------------------------------------->_______________] 79.84%3946 / 4931 [--------------------------------------------------------------->_______________] 80.02%3954 / 4931 [--------------------------------------------------------------->_______________] 80.19%3975 / 4931 [--------------------------------------------------------------->_______________] 80.61%4005 / 4931 [---------------------------------------------------------------->______________] 81.22%4012 / 4931 [---------------------------------------------------------------->______________] 81.36%4021 / 4931 [---------------------------------------------------------------->______________] 81.55%4023 / 4931 [---------------------------------------------------------------->______________] 81.59%4024 / 4931 [---------------------------------------------------------------->______________] 81.61%4030 / 4931 [---------------------------------------------------------------->______________] 81.73%4035 / 4931 [---------------------------------------------------------------->______________] 81.83%4044 / 4931 [---------------------------------------------------------------->______________] 82.01%4049 / 4931 [---------------------------------------------------------------->______________] 82.11%4053 / 4931 [---------------------------------------------------------------->______________] 82.19%4067 / 4931 [----------------------------------------------------------------->_____________] 82.48%4073 / 4931 [----------------------------------------------------------------->_____________] 82.60%4085 / 4931 [----------------------------------------------------------------->_____________] 82.84%4097 / 4931 [----------------------------------------------------------------->_____________] 83.09%4108 / 4931 [----------------------------------------------------------------->_____________] 83.31%4133 / 4931 [------------------------------------------------------------------>____________] 83.82%4137 / 4931 [------------------------------------------------------------------>____________] 83.90%4144 / 4931 [------------------------------------------------------------------>____________] 84.04%4154 / 4931 [------------------------------------------------------------------>____________] 84.24%4173 / 4931 [------------------------------------------------------------------>____________] 84.63%4205 / 4931 [------------------------------------------------------------------->___________] 85.28%4212 / 4931 [------------------------------------------------------------------->___________] 85.42%4218 / 4931 [------------------------------------------------------------------->___________] 85.54%4223 / 4931 [------------------------------------------------------------------->___________] 85.64%4224 / 4931 [------------------------------------------------------------------->___________] 85.66%4230 / 4931 [------------------------------------------------------------------->___________] 85.78%4235 / 4931 [------------------------------------------------------------------->___________] 85.89%4244 / 4931 [------------------------------------------------------------------->___________] 86.07%4249 / 4931 [-------------------------------------------------------------------->__________] 86.17%4253 / 4931 [-------------------------------------------------------------------->__________] 86.25%4265 / 4931 [-------------------------------------------------------------------->__________] 86.49%4273 / 4931 [-------------------------------------------------------------------->__________] 86.66%4285 / 4931 [-------------------------------------------------------------------->__________] 86.90%4297 / 4931 [-------------------------------------------------------------------->__________] 87.14%4308 / 4931 [--------------------------------------------------------------------->_________] 87.37%4333 / 4931 [--------------------------------------------------------------------->_________] 87.87%4337 / 4931 [--------------------------------------------------------------------->_________] 87.95%4344 / 4931 [--------------------------------------------------------------------->_________] 88.10%4354 / 4931 [--------------------------------------------------------------------->_________] 88.30%4373 / 4931 [---------------------------------------------------------------------->________] 88.68%4405 / 4931 [---------------------------------------------------------------------->________] 89.33%4412 / 4931 [---------------------------------------------------------------------->________] 89.47%4418 / 4931 [---------------------------------------------------------------------->________] 89.60%4423 / 4931 [---------------------------------------------------------------------->________] 89.70%4424 / 4931 [---------------------------------------------------------------------->________] 89.72%4429 / 4931 [---------------------------------------------------------------------->________] 89.82%4433 / 4931 [----------------------------------------------------------------------->_______] 89.90%4444 / 4931 [----------------------------------------------------------------------->_______] 90.12%4449 / 4931 [----------------------------------------------------------------------->_______] 90.23%4453 / 4931 [----------------------------------------------------------------------->_______] 90.31%4464 / 4931 [----------------------------------------------------------------------->_______] 90.53%4473 / 4931 [----------------------------------------------------------------------->_______] 90.71%4485 / 4931 [----------------------------------------------------------------------->_______] 90.96%4497 / 4931 [------------------------------------------------------------------------>______] 91.20%4508 / 4931 [------------------------------------------------------------------------>______] 91.42%4529 / 4931 [------------------------------------------------------------------------>______] 91.85%4537 / 4931 [------------------------------------------------------------------------>______] 92.01%4544 / 4931 [------------------------------------------------------------------------>______] 92.15%4554 / 4931 [------------------------------------------------------------------------>______] 92.35%4572 / 4931 [------------------------------------------------------------------------->_____] 92.72%4605 / 4931 [------------------------------------------------------------------------->_____] 93.39%4612 / 4931 [------------------------------------------------------------------------->_____] 93.53%4616 / 4931 [------------------------------------------------------------------------->_____] 93.61%4623 / 4931 [-------------------------------------------------------------------------->____] 93.75%4624 / 4931 [-------------------------------------------------------------------------->____] 93.77%4629 / 4931 [-------------------------------------------------------------------------->____] 93.88%4633 / 4931 [-------------------------------------------------------------------------->____] 93.96%4644 / 4931 [-------------------------------------------------------------------------->____] 94.18%4649 / 4931 [-------------------------------------------------------------------------->____] 94.28%4653 / 4931 [-------------------------------------------------------------------------->____] 94.36%4664 / 4931 [-------------------------------------------------------------------------->____] 94.59%4673 / 4931 [-------------------------------------------------------------------------->____] 94.77%4685 / 4931 [--------------------------------------------------------------------------->___] 95.01%4697 / 4931 [--------------------------------------------------------------------------->___] 95.25%4707 / 4931 [--------------------------------------------------------------------------->___] 95.46%4729 / 4931 [--------------------------------------------------------------------------->___] 95.90%4737 / 4931 [--------------------------------------------------------------------------->___] 96.07%4744 / 4931 [---------------------------------------------------------------------------->__] 96.21%4753 / 4931 [---------------------------------------------------------------------------->__] 96.39%4768 / 4931 [---------------------------------------------------------------------------->__] 96.69%4805 / 4931 [---------------------------------------------------------------------------->__] 97.44%4812 / 4931 [----------------------------------------------------------------------------->_] 97.59%4816 / 4931 [----------------------------------------------------------------------------->_] 97.67%4823 / 4931 [----------------------------------------------------------------------------->_] 97.81%4824 / 4931 [----------------------------------------------------------------------------->_] 97.83%4829 / 4931 [----------------------------------------------------------------------------->_] 97.93%4833 / 4931 [----------------------------------------------------------------------------->_] 98.01%4844 / 4931 [----------------------------------------------------------------------------->_] 98.24%4849 / 4931 [----------------------------------------------------------------------------->_] 98.34%4853 / 4931 [----------------------------------------------------------------------------->_] 98.42%4864 / 4931 [----------------------------------------------------------------------------->_] 98.64%4873 / 4931 [------------------------------------------------------------------------------>] 98.82%4885 / 4931 [------------------------------------------------------------------------------>] 99.07%4897 / 4931 [------------------------------------------------------------------------------>] 99.31%4906 / 4931 [------------------------------------------------------------------------------>] 99.49%4929 / 4931 [------------------------------------------------------------------------------>] 99.96%4931 / 4931 [------------------------------------------------------------------------------] 100.00%开始下载测速（下载速度下限：10.00 MB/s，下载测速数量：2，下载测速队列：125）：
0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%0 / 2 [______________________________________________________________________________________] 0.00%Killed
2022-04-12 21:38:54: -----------end------------

**Comment by mingxiaoyu** [comment]
看错了。100的速度。如果是电信晚高峰 估计要找蛮久的时间。。要么等 要么减少速度。最后一方法是 白天在测试
