### ISSUE TITLE
可以支持Passwall2，Bypass，Helloworld吗？

### ISSUE THREAD

**Issue by lochuan** [mingxiaoyu/luci-app-cloudflarespeedtest#18]
Passwall2: https://github.com/xiaorouji/openwrt-passwall2
Bypass: https://github.com/kiddin9/openwrt-bypass
Helloword: https://github.com/jerrykuku/luci-app-vssr

这几个用户也挺多的，Passwall现在已经停止开发，原作者现在维护Passwall2，后面两个是两个比较流行的固件里的插件。

**Comment by mingxiaoyu** [comment]
目前没空啊 passwall2 这个可以搞搞
