### ISSUE TITLE
可否自动添加host

### ISSUE THREAD

**Issue by mjyhj** [mingxiaoyu/luci-app-cloudflarespeedtest#20]
例如，我局域网下 套了一个 cf的cdn。
emby.xxxx.cf

能否加一个host绑定，测速完自动把最快的IP104.16.204.101,添加host
emby.xxxx.cf 104.16.204.101

我手动添加host，发现用手机网络去ping 也是这个IP

**Comment by mingxiaoyu** [comment]
有意思 有空再议

**Comment by mingxiaoyu** [comment]
我能 弱弱的问句  op 21.02 在哪里设置host @mjyhj

**Comment by lijiazhiren** [comment]
https://github.com/sirpdboy/luci-app-advanced
可以安装这个来设置host

**Comment by lijiazhiren** [comment]
也可以看看这个
https://github.com/XIU2/CloudflareSpeedTest/issues/42#issuecomment-768273848

**Comment by lochuan** [comment]
对噢，这样不同的客户端都不需要分别兼容了，直接指定Host是个不错的点子

**Comment by mingxiaoyu** [comment]
我只有 op 21.02 。就基于这个来做 DHCP/DNS
@lochuan 这个最烦的是，测试不能走代理，这个一直没想到好的方案。 个个客户端对IPtable 处理也不一样，神烦这。如果都是gfw模式上网，几乎没什么， 就是选其他模式的上网，难处理

**Comment by mingxiaoyu** [comment]
https://github.com/mingxiaoyu/R1-Plus-LTS/releases/download/r1lts-2022.04.06-0058/luci-app-cloudflarespeedtest_1.4.5_all.ipk

谁可以去试试？？？
@lochuan  @lijiazhiren  @mjyhj

**Comment by lochuan** [comment]
@mingxiaoyu 试了一下，代码逻辑有些问题，push到dev吧，有空我改一下。判断某个服务有没有开启之后进行其他逻辑的那个if结构应该包含它下面恢复原来模式的那个if，不然就会造成只勾选enable host也会重启某个服务。

**Comment by mingxiaoyu** [comment]
@lochuan  已经push 到dev了。 先谢谢啦。 目测 不到星期天，我应该没空在看这玩意。 哎~昨天还义务加班了一会，太忙了。
