### ISSUE TITLE
运行的时候找不到脚本？

### ISSUE THREAD

**Issue by jamqiang** [mingxiaoyu/luci-app-cloudflarespeedtest#22]
报错是找不到脚本？ 请看截图
<img width="1154" alt="WX20220428-010223@2x" src="https://user-images.githubusercontent.com/104521327/165581780-340aea66-eb51-47d5-8c6d-9dd063636353.png">

**Comment by mingxiaoyu** [comment]
[没装依赖](https://github.com/immortalwrt-collections/openwrt-cdnspeedtest

自己下载适合自己的)
