### ISSUE TITLE
这个带依赖吗。为啥运行没有用

### ISSUE THREAD

**Issue by jyou123** [mingxiaoyu/luci-app-cloudflarespeedtest#28]

**Comment by jyou123** [comment]
/usr/bin/cdnspeedtest -sl 12 -url https://cloudflaremirrors.com/archlinux/iso/2022.03.01/archlinux-2022.03.01-x86_64.iso -o /usr/share/cloudflarespeedtestresult.txt -f /usr/share/CloudflareSpeedTest/ip.txt -tl 200 -tll 40 -n 200 -t 4 -dt 10 -dn 2
2022-05-04 16:52:58: -----------start----------
/usr/bin/cloudflarespeedtest/cloudflarespeedtest.sh: line 118: /usr/bin/cdnspeedtest: not found
2022-05-04 16:52:58: -----------end------------
2022-05-04 16:52:58: 设置passwall代理模式

**Comment by mingxiaoyu** [comment]
read me 写有 带依赖

https://github.com/immortalwrt-collections/openwrt-cdnspeedtest
