### ISSUE TITLE
多个域名的hosts怎么添加？

### ISSUE THREAD

**Issue by ceozero** [mingxiaoyu/luci-app-cloudflarespeedtest#39]
默认只有一行，，好像用逗号分隔多个域名不成功。。
是否可以添加多个域名？还是说只能用一个了？

**Comment by pigrass** [comment]
+1，希望增加这个功能，因为很多域名都会用cloudflare的服务

**Comment by mingxiaoyu** [comment]
哦 。有空就整。。

**Comment by longshang2012** [comment]
> 默认只有一行，，好像用逗号分隔多个域名不成功。。 是否可以添加多个域名？还是说只能用一个了？

域名之间好像加空格就行了

**Comment by wainyang** [comment]
这个刚需，一个ip没法故障转移，辛苦作者开发了

**Comment by mingxiaoyu** [comment]
#57
