### ISSUE TITLE
一些功能建议

### ISSUE THREAD

**Issue by wbry** [mingxiaoyu/luci-app-cloudflarespeedtest#4]
1.设定测速时间的设置增加填入cron设定，比如"0 6,18 * * *"，比较方便自定义测速时间的需求。
2.增加更多高级参数的设定，比如-t -dn -dt可以自定义下，缩短测速带来的连接数、带宽占用时间对当前网络可用性的影响。

感谢大佬

**Comment by mingxiaoyu** [comment]
这周貌似没空做
