### ISSUE TITLE
未找到默认 ping 值小于 200ms 导致自动设置 ip 为空

### ISSUE THREAD

**Issue by anai1943** [mingxiaoyu/luci-app-cloudflarespeedtest#40]
感谢作者开发的这么好用的插件，反馈一个 bug：
未启用高级模式，筛选 ip 时平均 ping 值默认不能高于 200ms，出现过 4000 多个 ip ping 值全都大于 200ms，这时会跳过测速，并把第三方应用设置内选中的节点的 ip 设置为空。希望作者有空验证下，感谢！

**Comment by mingxiaoyu** [comment]
谢谢反馈。 有空就去测试。
