### ISSUE TITLE
无法完成速度测试，速度一直是0

### ISSUE THREAD

**Issue by Seaking111** [mingxiaoyu/luci-app-cloudflarespeedtest#46]
![F8CC3E7B-B9FA-4b57-B8AA-F6AB5B7BBA39](https://user-images.githubusercontent.com/70312948/216605816-3c18c101-b871-444e-9a55-7b5803098c37.png)
不知道咋会事，在完成了延迟测试后下载测试就速度一直为0 更改了测速地址也一样，有可能哪里出问题了呢？

**Comment by hadow** [comment]
依赖装了吗？https://github.com/immortalwrt-collections/openwrt-cdnspeedtest

**Comment by mingxiaoyu** [comment]
去这里反馈 ： https://github.com/XIU2/CloudflareSpeedTest
