### ISSUE TITLE
解析线路建议默认

### ISSUE THREAD

**Issue by quanjindeng** [mingxiaoyu/luci-app-cloudflarespeedtest#5]
阿里云官网是这样说明的：`如果只有一个IP地址或CNAME域名，请务必选择【默认】。
默认：必填！未匹配到智能解析线路时，返回【默认】线路设置结果。 `

我测试了下，选择我宽带运营商（移动）解析路线，等待很久域名都没有dns地址。
手动添加一个新域名解析，使用默认线路，立即可用；将原来的移动路线改为默认后，也在一两分钟后可用。

所以还是建议添加一下模式线路吧！感谢

**Comment by mingxiaoyu** [comment]
我是用partner 加的。必须带默认。不知道还可以这样玩。。有空加上去。

**Comment by mingxiaoyu** [comment]
#6 
加入了
