### ISSUE TITLE
关于修改host的策略问题

### ISSUE THREAD

**Issue by djniche** [mingxiaoyu/luci-app-cloudflarespeedtest#52]
passwall1 分流模式 测速时关闭passwall
但是当测速完成,开启passwall修改好host,这个逻辑有点问题.
完整测速结果已写入 /usr/share/cloudflarespeedtestresult.txt 文件，可使用记事本/表格软件查看。
2023-03-15 13:43:12: -----------end------------
2023-03-15 13:43:21: passwall重启完成
2023-03-15 13:43:22: HOST 完成

虽然op上ping已经是修改后的host了.
但是passwall对dns做了劫持
先开启了passwall后,host IP不会在客户端生效
必须要重新保存一下passwall ,客户端设备才会生效 
否则无论怎么清空缓存,还会是之前的ip.
希望改成,HOST 完成之后再开启passwall.

感谢作者大佬

**Comment by djniche** [comment]
已经改好了 测试没问题,用passwall分流的请自行复制替换 /usr/bin/cloudflarespeedtest/cloudflarespeedtest.sh 里边的内容

https://raw.githubusercontent.com/djniche/cfsh/main/cloudflarespeedtest.sh

**Comment by mingxiaoyu** [comment]
能搞个PR 不。。。。。

**Comment by djniche** [comment]
> 能搞个PR 不。。。。。

你看看行不行...我代码比较白痴,只会简单修改.. 完全不懂github逻辑

**Comment by mingxiaoyu** [comment]
#53 
没注意你换了文件夹的位置。。这个不需要

**Comment by djniche** [comment]
> #53 没注意你换了文件夹的位置。。这个不需要

我刚才遇到了2.2.1版本st测速为0的问题.换了好多个测速节点都不行.
最后我把 cloudflarespeedtest.sh的command="/usr/bin/cdnspeedtest 修改到了我下载的最新版st可执行文件进行测速,发现正常了...我觉得你还不如直接把CloudflareSpeedTest的X86可执行文件直接打包进ipk...
或者多加一个下载的最新版本执行文件的选项..自动下载解压最新版本的CloudflareSpeedTest

![1](https://user-images.githubusercontent.com/71032074/225265217-91d8a9c4-e1ed-464c-b305-12804c3e5603.png)
![2](https://user-images.githubusercontent.com/71032074/225265253-3662ca19-23a0-45dc-8b97-d48ccffd272e.png)


我又换到cdnspeedtest测试 确认2.2.1下载速度为0 
/usr/bin/cdnspeedtest -sl 0 -url https://do.geigei.gq/1gb.test -o /usr/share/cloudflarespeedtestresult.txt -f /usr/share/CloudflareSpeedTest/ip.txt -tl 400 -tll 80 -n 200 -t 4 -dt 10 -dn 10
2023-03-15 18:07:19: -----------start----------
# XIU2/CloudflareSpeedTest v2.2.1 

![3](https://user-images.githubusercontent.com/71032074/225278209-8f64ebf1-c3b4-41e6-9a29-6cdf989590be.png)
