### ISSUE TITLE
需求更新

### ISSUE THREAD

**Issue by hello150420** [mingxiaoyu/luci-app-cloudflarespeedtest#7]
可否增加功能:1自定义ip文件。2.自定义端口，不仅限443

**Comment by mingxiaoyu** [comment]
自定义ip文件
不想做
自己手动替换文件即可。
自定义端口已经加入

**Comment by teddy780102** [comment]
手工替换文件位置和名称，还望指导下

**Comment by mingxiaoyu** [comment]
IPV4 的 /usr/share/CloudflareSpeedTest/ip.txt
IPV6 的在同一个目录
@hello150420
